version: '3.8'

services:
  postgres:
    image: postgres:15
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: password123
      POSTGRES_DB: nestjs_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - app_network

  keycloak:
    image: quay.io/keycloak/keycloak:latest
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
    ports:
      - "8080:8080"
    command: start-dev
    depends_on:
      - postgres
    networks:
      - app_network
    
  api:
    build:
      context: ./back
      dockerfile: Dockerfile
    container_name: nestjs_api
    ports:
      - "3000:3000"
    extra_hosts:
      - "localhost:host-gateway"
    environment:
      DATABASE_URL: postgresql://admin:password123@postgres:5432/nestjs_db?schema=public
      KEYCLOAK_AUTH_SERVER_URL: http://localhost:8080
      KEYCLOAK_REALM: shaderlab
      KEYCLOAK_CLIENT_ID: shaderlab_client
    depends_on:
      - postgres
      - keycloak
    networks:
      - app_network

networks:
  app_network:
    driver: bridge

volumes:
  postgres_data:   
