export const NODE_CATALOG = [
  {
    category: "Math",
    colorVar: "var(--cat-math)",
    items: [
      {
        type: "add",
        label: "Add",
        icon: "+",
        desc: "Sum two numbers",
        inputs: ["a", "b"],
        outputs: ["result"],
      },
      {
        type: "subtract",
        label: "Subtract",
        icon: "−",
        desc: "Subtract b from a",
        inputs: ["a", "b"],
        outputs: ["result"],
      },
      {
        type: "multiply",
        label: "Multiply",
        icon: "×",
        desc: "Multiply two numbers",
        inputs: ["a", "b"],
        outputs: ["result"],
      },
      {
        type: "divide",
        label: "Divide",
        icon: "÷",
        desc: "Divide a by b",
        inputs: ["a", "b"],
        outputs: ["result"],
      },
      {
        type: "abs",
        label: "Abs",
        icon: "|x|",
        desc: "Absolute value",
        inputs: ["x"],
        outputs: ["result"],
      },
      {
        type: "clamp",
        label: "Clamp",
        icon: "⌈⌋",
        desc: "Clamp to min/max range",
        inputs: ["x", "min", "max"],
        outputs: ["result"],
      },
    ],
  },
  {
    category: "Logic",
    colorVar: "var(--cat-logic)",
    items: [
      {
        type: "and",
        label: "AND",
        icon: "∧",
        desc: "Logical AND",
        inputs: ["a", "b"],
        outputs: ["out"],
      },
      {
        type: "or",
        label: "OR",
        icon: "∨",
        desc: "Logical OR",
        inputs: ["a", "b"],
        outputs: ["out"],
      },
      {
        type: "not",
        label: "NOT",
        icon: "¬",
        desc: "Logical NOT",
        inputs: ["in"],
        outputs: ["out"],
      },
      {
        type: "compare",
        label: "Compare",
        icon: "⟺",
        desc: "Compare two values",
        inputs: ["a", "b"],
        outputs: ["<", ">", "="],
      },
      {
        type: "branch",
        label: "Branch",
        icon: "⑂",
        desc: "If/else gate",
        inputs: ["cond", "t", "f"],
        outputs: ["out"],
      },
    ],
  },
  {
    category: "Data",
    colorVar: "var(--cat-data)",
    items: [
      {
        type: "number",
        label: "Number",
        icon: "#",
        desc: "Constant number",
        inputs: [],
        outputs: ["value"],
      },
      {
        type: "string",
        label: "String",
        icon: '"',
        desc: "Constant string",
        inputs: [],
        outputs: ["value"],
      },
      {
        type: "boolean",
        label: "Boolean",
        icon: "◉",
        desc: "True / false toggle",
        inputs: [],
        outputs: ["value"],
      },
      {
        type: "array",
        label: "Array",
        icon: "[]",
        desc: "Collect into array",
        inputs: ["…"],
        outputs: ["array"],
      },
      {
        type: "object",
        label: "Object",
        icon: "{}",
        desc: "Build key-value map",
        inputs: ["…"],
        outputs: ["object"],
      },
    ],
  },
  {
    category: "I/O",
    colorVar: "var(--cat-io)",
    items: [
      {
        type: "input",
        label: "Input",
        icon: "→",
        desc: "Graph input port",
        inputs: [],
        outputs: ["value"],
      },
      {
        type: "output",
        label: "Output",
        icon: "←",
        desc: "Graph output port",
        inputs: ["value"],
        outputs: [],
      },
      {
        type: "log",
        label: "Log",
        icon: "📋",
        desc: "Log value to console",
        inputs: ["value"],
        outputs: [],
      },
      {
        type: "display",
        label: "Display",
        icon: "👁",
        desc: "Show value in panel",
        inputs: ["value"],
        outputs: [],
      },
    ],
  },
  {
    category: "Utility",
    colorVar: "var(--cat-util)",
    items: [
      {
        type: "merge",
        label: "Merge",
        icon: "⇒",
        desc: "Merge two streams",
        inputs: ["a", "b"],
        outputs: ["out"],
      },
      {
        type: "split",
        label: "Split",
        icon: "⇐",
        desc: "Split into streams",
        inputs: ["in"],
        outputs: ["a", "b"],
      },
      {
        type: "delay",
        label: "Delay",
        icon: "⏱",
        desc: "Delay propagation",
        inputs: ["in"],
        outputs: ["out"],
      },
      {
        type: "comment",
        label: "Comment",
        icon: "✎",
        desc: "Annotation node",
        inputs: [],
        outputs: [],
      },
    ],
  },
];
