/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthRouteImport } from './routes/_auth'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthProfileRouteImport } from './routes/_auth/profile'
import { Route as AuthDashboardRouteImport } from './routes/_auth/dashboard'
import { Route as AuthCreateProjectRouteImport } from './routes/_auth/createProject'
import { Route as AuthProjectIdEditorRouteImport } from './routes/_auth/$projectId.editor'
import { Route as AuthProjectIdEditProjectRouteImport } from './routes/_auth/$projectId.editProject'

const AuthRoute = AuthRouteImport.update({
  id: '/_auth',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthProfileRoute = AuthProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => AuthRoute,
} as any)
const AuthDashboardRoute = AuthDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthRoute,
} as any)
const AuthCreateProjectRoute = AuthCreateProjectRouteImport.update({
  id: '/createProject',
  path: '/createProject',
  getParentRoute: () => AuthRoute,
} as any)
const AuthProjectIdEditorRoute = AuthProjectIdEditorRouteImport.update({
  id: '/$projectId/editor',
  path: '/$projectId/editor',
  getParentRoute: () => AuthRoute,
} as any)
const AuthProjectIdEditProjectRoute =
  AuthProjectIdEditProjectRouteImport.update({
    id: '/$projectId/editProject',
    path: '/$projectId/editProject',
    getParentRoute: () => AuthRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/createProject': typeof AuthCreateProjectRoute
  '/dashboard': typeof AuthDashboardRoute
  '/profile': typeof AuthProfileRoute
  '/$projectId/editProject': typeof AuthProjectIdEditProjectRoute
  '/$projectId/editor': typeof AuthProjectIdEditorRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/createProject': typeof AuthCreateProjectRoute
  '/dashboard': typeof AuthDashboardRoute
  '/profile': typeof AuthProfileRoute
  '/$projectId/editProject': typeof AuthProjectIdEditProjectRoute
  '/$projectId/editor': typeof AuthProjectIdEditorRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_auth': typeof AuthRouteWithChildren
  '/_auth/createProject': typeof AuthCreateProjectRoute
  '/_auth/dashboard': typeof AuthDashboardRoute
  '/_auth/profile': typeof AuthProfileRoute
  '/_auth/$projectId/editProject': typeof AuthProjectIdEditProjectRoute
  '/_auth/$projectId/editor': typeof AuthProjectIdEditorRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/createProject'
    | '/dashboard'
    | '/profile'
    | '/$projectId/editProject'
    | '/$projectId/editor'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/createProject'
    | '/dashboard'
    | '/profile'
    | '/$projectId/editProject'
    | '/$projectId/editor'
  id:
    | '__root__'
    | '/'
    | '/_auth'
    | '/_auth/createProject'
    | '/_auth/dashboard'
    | '/_auth/profile'
    | '/_auth/$projectId/editProject'
    | '/_auth/$projectId/editor'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthRoute: typeof AuthRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_auth': {
      id: '/_auth'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth/profile': {
      id: '/_auth/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof AuthProfileRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/dashboard': {
      id: '/_auth/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthDashboardRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/createProject': {
      id: '/_auth/createProject'
      path: '/createProject'
      fullPath: '/createProject'
      preLoaderRoute: typeof AuthCreateProjectRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/$projectId/editor': {
      id: '/_auth/$projectId/editor'
      path: '/$projectId/editor'
      fullPath: '/$projectId/editor'
      preLoaderRoute: typeof AuthProjectIdEditorRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/$projectId/editProject': {
      id: '/_auth/$projectId/editProject'
      path: '/$projectId/editProject'
      fullPath: '/$projectId/editProject'
      preLoaderRoute: typeof AuthProjectIdEditProjectRouteImport
      parentRoute: typeof AuthRoute
    }
  }
}

interface AuthRouteChildren {
  AuthCreateProjectRoute: typeof AuthCreateProjectRoute
  AuthDashboardRoute: typeof AuthDashboardRoute
  AuthProfileRoute: typeof AuthProfileRoute
  AuthProjectIdEditProjectRoute: typeof AuthProjectIdEditProjectRoute
  AuthProjectIdEditorRoute: typeof AuthProjectIdEditorRoute
}

const AuthRouteChildren: AuthRouteChildren = {
  AuthCreateProjectRoute: AuthCreateProjectRoute,
  AuthDashboardRoute: AuthDashboardRoute,
  AuthProfileRoute: AuthProfileRoute,
  AuthProjectIdEditProjectRoute: AuthProjectIdEditProjectRoute,
  AuthProjectIdEditorRoute: AuthProjectIdEditorRoute,
}

const AuthRouteWithChildren = AuthRoute._addFileChildren(AuthRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthRoute: AuthRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
